//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections; 
using System;
using System.IO;

namespace AssemblyCSharp
{
	public class MoveForward : MonoBehaviour
		{
				public MoveForward ()
				{
				}

		private Transform cameraPosition; 

		void Start () {
			cameraPosition = GameObject.Find("Main Camera").transform;
		}
		
		void Update () {

			if (Input.GetButton("Jump"))
			{
				// this.Transform(Vector3.forward * Time.deltaTime * 25);
				// transform.position = cameraPosition.position + new Vector3(cameraDistance, cameraHeight, -cameraDistance); 
				cameraPosition.position += Vector3.forward * Time.deltaTime * 2; // 25;
				// transform.LookAt(cameraPosition); 
			}
			
		}
		}
}

