//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace AssemblyCSharp
{
	public class FixedRotation : MonoBehaviour
		{
			Quaternion rotation;
			public FixedRotation ()
			{

			}
			
			void Awake()
			{
				rotation = transform.rotation;
			}
			
			void LateUpdate()
			{
				transform.rotation = rotation;
			}
		}
}

